import os
# os.rename('1.py', '2.py')
# print(os.getcwd())
# os.mkdir('k1')
# os.chdir('k1')
# os.makedirs('a1/a2/a3')
# os.remove()
# os.chdir('a1/a2/a3')
# print(os.getcwd())
# os.remove('23.py')
# os.chdir('a1/a2')
# print(os.getcwd())
# os.rmdir('a3')
# os.removedirs('a1/a2')
os.rmdir('k1')